package com.jobportal.model;

public enum Role {
    ROLE_JOB_SEEKER,
    ROLE_RECRUITER,
    ROLE_ADMIN,
    ROLE_HR_MANAGER,
    ROLE_INTERVIEWER,
    ROLE_COMPANY_ADMIN,
    ROLE_HIRING_MANAGER,
    ROLE_TECHNICAL_LEAD,
    ROLE_SOURCER,
    ROLE_DEPARTMENT_HEAD,
    ROLE_FINANCE_MANAGER,
    ROLE_FRESHER,
    ROLE_EXPERIENCED,
    ROLE_MODERATOR,
    ROLE_SUPPORT_AGENT
}
